<?php

/**
 * This is the model base class for the table "Weapon".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Weapon".
 *
 * Columns in table "Weapon" available as properties of the model,
 * followed by relations of table "Weapon" available as properties of the model.
 *
 * @property string $id
 * @property string $class
 * @property string $name
 * @property string $description
 * @property double $buy
 * @property double $sell
 * @property integer $damage
 * @property integer $weight
 *
 * @property Hero[] $heros
 */
abstract class BaseWeapon extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function getDbConnection()
    {
        return Yii::app()->dbGame;
    }

	public function tableName() {
		return 'Weapon';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Weapon|Weapons', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('damage, weight', 'numerical', 'integerOnly'=>true),
			array('buy, sell', 'numerical'),
			array('class', 'length', 'max'=>30),
			array('name', 'length', 'max'=>50),
			array('description', 'length', 'max'=>100),
			array('class, name, description, buy, sell, damage, weight', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, class, name, description, buy, sell, damage, weight', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'heros' => array(self::HAS_MANY, 'Hero', 'weapon_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'class' => Yii::t('app', 'Class'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'buy' => Yii::t('app', 'Buy'),
			'sell' => Yii::t('app', 'Sell'),
			'damage' => Yii::t('app', 'Damage'),
			'weight' => Yii::t('app', 'Weight'),
			'heros' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('class', $this->class, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('buy', $this->buy);
		$criteria->compare('sell', $this->sell);
		$criteria->compare('damage', $this->damage);
		$criteria->compare('weight', $this->weight);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}