<?php

/**
 * This is the model base class for the table "country".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Country".
 *
 * Columns in table "country" available as properties of the model,
 * followed by relations of table "country" available as properties of the model.
 *
 * @property string $id
 * @property string $shortName
 * @property string $fullName
 * @property string $countryCode
 *
 * @property User[] $users
 */
abstract class BaseCountry extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'country';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Country|Countries', $n);
	}

	public static function representingColumn() {
		return 'shortName';
	}

	public function rules() {
		return array(
			array('shortName, fullName', 'length', 'max'=>100),
			array('countryCode', 'length', 'max'=>2),
			array('shortName, fullName, countryCode', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, shortName, fullName, countryCode', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'users' => array(self::HAS_MANY, 'User', 'country'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'shortName' => Yii::t('app', 'Short Name'),
			'fullName' => Yii::t('app', 'Full Name'),
			'countryCode' => Yii::t('app', 'Country Code'),
			'users' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('shortName', $this->shortName, true);
		$criteria->compare('fullName', $this->fullName, true);
		$criteria->compare('countryCode', $this->countryCode, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}