<?php

/**
 * This is the model base class for the table "Game".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Game".
 *
 * Columns in table "Game" available as properties of the model,
 * followed by relations of table "Game" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $description
 * @property double $map_size_x
 * @property double $map_size_y
 *
 * @property Hero[] $heros
 */
abstract class BaseGame extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function getDbConnection()
    {
        return Yii::app()->dbGame;
    }

	public function tableName() {
		return 'Game';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Game|Games', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('map_size_x, map_size_y', 'numerical'),
			array('name', 'length', 'max'=>50),
			array('description', 'length', 'max'=>100),
			array('name, description, map_size_x, map_size_y', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, description, map_size_x, map_size_y', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'heros' => array(self::HAS_MANY, 'Hero', 'game_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'map_size_x' => Yii::t('app', 'Map Size X'),
			'map_size_y' => Yii::t('app', 'Map Size Y'),
			'heros' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('map_size_x', $this->map_size_x);
		$criteria->compare('map_size_y', $this->map_size_y);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}